In [4]:
import pandas as pd
import sqlite3

conn = sqlite3.connect('data/raw/project-db.db')

In [5]:
query = """
SELECT name FROM sqlite_master WHERE type='table';
"""
pd.read_sql_query(query, conn)    # List all tables in the database

          name
0  departments
1      regions
2    employees
3    customers
4        sales

In [17]:
query = """
SELECT * FROM departments
LIMIT 10;
"""
pd.read_sql_query(query, conn)

          department     division
0           Clothing         Home
1            Grocery         Home
2              Decor         Home
3          Furniture         Home
4          Computers  Electronics
5      Device Repair  Electronics
6   Phones & Tablets  Electronics
7             Garden     Outdoors
8  Camping & Fishing     Outdoors
9             Sports     Outdoors

In [6]:
query = """
SELECT * FROM customers
LIMIT 10;
"""
pd.read_sql_query(query, conn)    # Display the first 10 rows of the customers

,Customer_ID,Bracket_cust_id,Customer_Name,Segment,Age,Country,City,State,Postal_Code,Regio
0,CG-12520,(CG-12520),Claire Gute,Consumer,67,United States,Henderson,Kentucky,42420,South
1,DV-13045,(DV-13045),Darrin Van Huff,Corporate,31,United States,Los Angeles,California,90036,West
2,SO-20335,(SO-20335),Sean O'Donnell,Consumer,65,United States,Fort Lauderdale,Florida,33311,South
3,BH-11710,(BH-11710),Brosina Hoffman,Consumer,20,United States,Los Angeles,California,90032,West
4,AA-10480,(AA-10480),Andrew Allen,Consumer,50,United States,Concord,North Carolina,28027,South
5,IM-15070,(IM-15070),Irene Maddox,Consumer,66,United States,Seattle,Washington,98103,West
6,HP-14815,(HP-14815),Harold Pawlan,Home Office,20,United States,Fort Worth,Texas,76106,Central
7,PK-19075,(PK-19075),Pete Kriz,Consumer,46,United States,Madison,Wisconsin,53711,Central
8,AG-10270,(AG-10270),Alejandro Grove,Consumer,18,None,West Jordan,Utah,84084,West
9,ZD-21925,(ZD-21925),Zuschuss Donatelli,Consumer,66,United States,San Francisco,California,94109,West

In [7]:
query = """
SELECT * FROM sales
LIMIT 10;
"""
pd.read_sql_query(query, conn)    # Display the first 10 rows of the sales

,Order_line,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Product_ID,Category,Sub_Category,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,FUR-BO-10001798,Furniture,Bookcases,261.96,2,0.00,41.91
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,FUR-CH-10000454,Furniture,Chairs,731.94,3,0.00,219.58
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,OFF-LA-10000240,Office Supplies,Labels,14.62,2,0.00,6.87
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,FUR-TA-10000577,Furniture,Tables,957.58,5,0.45,-383.03
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,OFF-ST-10000760,Office Supplies,Storage,22.37,2,0.20,2.52
5,6,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,FUR-FU-10001487,Furniture,Furnishings,48.86,7,0.00,14.17
6,7,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,OFF-AR-10002833,Office Supplies,Art,7.28,4,0.00,1.97
7,8,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,TEC-PH-10002275,Technology,Phones,907.15,6,0.20,90.72
8,9,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,OFF-BI-10003910,Office Supplies,Binders,18.50,3,0.20,5.78
9,10,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,OFF-AP-10002892,Office Supplies,Appliances,114.90,5,0.00,34.47

In [21]:
query = """
SELECT * FROM employees
LIMIT 10;
"""
pd.read_sql_query(query, conn)    # Display the first 10 rows of the employees

,employee_id,first_name,last_name,email,hire_date,department,gender,salary,region_id
0,1,Berrie,Manueau,bmanueau0@dion.ne.jp,2006-04-20,Sports,F,154864,4
1,2,Aeriell,McNee,amcnee1@google.es,2009-01-26,Tools,F,56752,3
2,3,Sydney,Symonds,ssymonds2@hhs.gov,2010-05-17,Clothing,F,95313,4
3,4,Avrom,Rowantree,None,2014-08-02,Phones & Tablets,M,119674,7
4,5,Feliks,Morffew,fmorffew4@a8.net,2003-01-14,Computers,M,55307,5
5,6,Bethena,Trow,btrow5@technorati.com,2003-06-08,Sports,F,134501,3
6,7,Ardeen,Curwood,acurwood6@1und1.de,2006-02-19,Clothing,F,28995,7
7,8,Seline,Dubber,sdubber7@t-online.de,2012-05-28,Phones & Tablets,F,101066,3
8,9,Dayle,Trail,dtrail8@tamu.edu,2003-03-01,First Aid,F,82753,1
9,10,Redford,Roberti,None,2008-07-21,Clothing,M,72225,7

In [11]:
query = """
SELECT department, 
       employee_id,
       first_name || ' ' || last_name AS employee_name, 
       salary, 
       AVG(salary) OVER (PARTITION BY department) AS avg_department_salary
FROM employees
ORDER BY department DESC
LIMIT 10;
"""
pd.read_sql_query(query, conn)    # Display the average salary per department using window functions (partition by department)

  department  employee_id         employee_name  salary  avg_department_salary
0   Vitamins           39         Mikael Kybbye   52642                90358.0
1   Vitamins           71          Tobi Lamasna   68925                90358.0
2   Vitamins          235          Cary Kelshaw  139145                90358.0
3   Vitamins          288      Buckie Jodrellec   30289                90358.0
4   Vitamins          292          Norri Tandey  158847                90358.0
5   Vitamins          310  Archambault Marriner  123287                90358.0
6   Vitamins          332           Ame Pateman   21931                90358.0
7   Vitamins          343      Maridel Whellans   24884                90358.0
8   Vitamins          344      Daren Cattermull   67549                90358.0
9   Vitamins          416        Manolo Garling  146293                90358.0

In [ ]:
query = """
SELECT department,
       employee_name,
       salary
FROM (
    SELECT department,
           first_name || ' ' || last_name AS employee_name,
           salary,
           -- Create a separate ranking within each department. Now we can use the ranking to filter out the top earners in each department 
           -- since we have a ranking for each employee within their department inside the subquery (salary_rank table).
           RANK() OVER (
               PARTITION BY department
               ORDER BY salary DESC
           ) AS salary_rank
    FROM employees
) AS ranked_employees
WHERE salary_rank = 1;
"""
pd.read_sql_query(query, conn)

           department      employee_name  salary
0          Automotive         Mill Makey  162522
1              Beauty   Orland Backhouse  162845
2               Books   Sephira Jarville  159561
3             Camping    Riley Yellowlea  166569
4   Children Clothing    Yancy Marunchak  158546
5            Clothing   Jacklyn Finlator  166976
6           Computers      Brandise Jans  163512
7           Cosmetics        Cal Goacher  162454
8               Decor      Jabez Ghidini  153849
9       Device Repair    Michail Huggard  164355
10          First Aid        Rob Medwell  164011
11          Furniture    Wrennie Bealing  160170
12              Games     Patty Halfhead  152615
13             Garden       Bunny Sawkin  163361
14            Grocery         Ev Wessell  164582
15            Jewelry    Hendrik Garbutt  163794
16        Maintenance     Sofia Clements  154140
17             Movies   Rafaello Bridson  159463
18              Music   Carissa Gabbitus  166765
19           Pharmacy  Lauren Bertenshaw  166016
20   Phones & Tablets   Ingrim Simonitto  158148
21           Plumbing       Del Eglinton  145652
22           Security      Kincaid Bader  162233
23             Sports      Lucy Olifaunt  165660
24              Tools        Kelby Nudde  156672
25               Toys      Zeke Keyworth  163688
26           Vitamins     Elvera Tinline  163933

In [ ]:
# 2nd way using FIRST_VALUE() Window Function and Common Table Expression (CTE)
query = """
WITH max_salary_per_department AS (
    SELECT department,
           first_name || ' ' || last_name AS employee_name,
           salary,
           FIRST_VALUE(salary) OVER(
                    PARTITION BY department 
                    ORDER BY salary DESC) AS highest_employee_salary_per_department
FROM employees
)

SELECT employee_name, 
       department, 
       salary
FROM max_salary_per_department
WHERE salary = highest_employee_salary_per_department
GROUP BY employee_name, department
ORDER BY salary DESC;
"""

pd.read_sql_query(query, conn)

        employee_name         department  salary
0    Jacklyn Finlator           Clothing  166976
1    Carissa Gabbitus              Music  166765
2     Riley Yellowlea            Camping  166569
3   Lauren Bertenshaw           Pharmacy  166016
4       Lucy Olifaunt             Sports  165660
5          Ev Wessell            Grocery  164582
6     Michail Huggard      Device Repair  164355
7         Rob Medwell          First Aid  164011
8      Elvera Tinline           Vitamins  163933
9     Hendrik Garbutt            Jewelry  163794
10      Zeke Keyworth               Toys  163688
11      Brandise Jans          Computers  163512
12       Bunny Sawkin             Garden  163361
13   Orland Backhouse             Beauty  162845
14         Mill Makey         Automotive  162522
15        Cal Goacher          Cosmetics  162454
16      Kincaid Bader           Security  162233
17    Wrennie Bealing          Furniture  160170
18   Sephira Jarville              Books  159561
19   Rafaello Bridson             Movies  159463
20    Yancy Marunchak  Children Clothing  158546
21   Ingrim Simonitto   Phones & Tablets  158148
22        Kelby Nudde              Tools  156672
23     Sofia Clements        Maintenance  154140
24      Jabez Ghidini              Decor  153849
25     Patty Halfhead              Games  152615
26       Del Eglinton           Plumbing  145652

In [ ]:
query = """
-- Assign numbers to each row of the department for the Entertainment division

SELECT *,
    ROW_NUMBER() OVER() AS Row_N
FROM departments
WHERE divisIon = 'Entertainment'
ORDER BY Row_N ASC;
"""
pd.read_sql_query(query, conn)

  department       division  Row_N
0      Books  Entertainment      1
1      Games  Entertainment      2
2      Music  Entertainment      3
3     Movies  Entertainment      4

In [ ]:
query = """
-- Ordering in- and outside the OVER() clause

SELECT employee_id, 
       first_name, 
       hire_date, 
       salary, 
       department,
       ROW_NUMBER() OVER(
                     ORDER BY hire_date ASC, salary DESC
                     ) AS Row_N
FROM employees
WHERE department = 'Sports'
ORDER BY employee_id;
"""

pd.read_sql_query(query, conn)

    employee_id first_name   hire_date  salary department  Row_N
0             1     Berrie  2006-04-20  154864     Sports     10
1             6    Bethena  2003-06-08  134501     Sports      1
2            34       Lucy  2005-02-07  165660     Sports      8
3            51     Norine  2008-08-22   66488     Sports     16
4            77    Maurice  2006-01-08   67615     Sports      9
5            89  Claudetta  2011-08-24  157802     Sports     23
6           156     Joleen  2004-10-24   29838     Sports      7
7           164   Benjamin  2006-11-13   21735     Sports     12
8           190     Averyl  2014-10-12  118250     Sports     28
9           191   Marjorie  2012-08-17  130147     Sports     24
10          206      Cyndi  2008-05-29   71364     Sports     14
11          211    Michail  2011-03-07  103760     Sports     21
12          337       Eden  2010-11-28   30836     Sports     20
13          398    Gustavo  2014-03-01   77085     Sports     25
14          423        Gav  2008-07-18  115978     Sports     15
15          461    Stefano  2015-05-16   61867     Sports     29
16          474      Bryna  2011-04-18   30762     Sports     22
17          502     Darbie  2015-10-24   98668     Sports     32
18          524       Esme  2003-08-02   51318     Sports      3
19          540       Cody  2003-10-05   87813     Sports      4
20          543   Sherwynd  2010-09-19  164470     Sports     19
21          555      Andra  2003-06-21  150195     Sports      2
22          573        Nan  2009-08-06   28029     Sports     17
23          598     Darrin  2004-01-17  142943     Sports      5
24          636       Adam  2015-09-15   67057     Sports     31
25          666     Dreddy  2015-10-28   38793     Sports     33
26          752     Melita  2006-09-17  136922     Sports     11
27          784    Starlin  2004-09-07   38120     Sports      6
28          832    Monique  2016-06-13  150061     Sports     34
29          846    Stanley  2009-11-17  151814     Sports     18
30          847    Gweneth  2014-09-12   29047     Sports     27
31          924       Lynn  2015-09-03   46529     Sports     30
32          979     Delila  2007-06-30   27064     Sports     13
33          991   Marquita  2014-09-07   38909     Sports     26

In [26]:
query = """
-- Retrieve the employee_id, first_name, hire_date of employees for different departments
-- Order by the hire_date

SELECT employee_id, 
       first_name, 
       department, 
       hire_date,
ROW_NUMBER() OVER(
              PARTITION BY department
		ORDER BY hire_date
              ) AS Row_N
FROM employees
ORDER BY department
LIMIT 10;
"""
pd.read_sql_query(query, conn)

   employee_id first_name  department   hire_date  Row_N
0          927  Maryellen  Automotive  2003-04-19      1
1          840  Archibold  Automotive  2003-04-26      2
2          988       Tabb  Automotive  2003-05-02      3
3          648     Abbott  Automotive  2003-06-05      4
4          305    Ladonna  Automotive  2003-08-10      5
5          126     Roslyn  Automotive  2003-08-11      6
6          274    Lorelle  Automotive  2004-01-27      7
7          515      Cybil  Automotive  2004-04-01      8
8          249   Sterling  Automotive  2004-09-02      9
9          456   Jessalyn  Automotive  2004-10-03     10

In [45]:
query = """
-- Create a common table expression to retrieve the customer_id, customer_name, segment and how many 
-- times the customer has purchased from the mall 

WITH customer_purchase AS (
	SELECT s.customer_id, 
           c.customer_name, 
           c.segment,
	       COUNT(*) AS purchase_count
	FROM sales s
	JOIN customers c
	ON s.customer_id = c.customer_id
	GROUP BY s.customer_id, c.customer_name, c.segment
	ORDER BY s.customer_id)

-- Number each customer by how many purchases they've made

SELECT *,
	   ROW_NUMBER() OVER (
    				ORDER BY purchase_count DESC
                    ) AS Row_N
FROM customer_purchase
ORDER BY purchase_count DESC;    
"""
pd.read_sql_query(query, conn)

    customer_id        customer_name      segment  purchase_count  Row_N
0      WB-21850        William Brown     Consumer              37      1
1      JL-15835             John Lee     Consumer              34      2
2      MA-17560         Matt Abelman  Home Office              34      3
3      PP-18955           Paul Prost  Home Office              34      4
4      CK-12205  Chloris Kastensmidt     Consumer              32      5
..          ...                  ...          ...             ...    ...
788    AO-10810    Anthony O'Donnell    Corporate               1    789
789    CJ-11875         Carl Jackson    Corporate               1    790
790    JR-15700       Jocasta Rupert     Consumer               1    791
791    LD-16855         Lela Donovan    Corporate               1    792
792    RE-19405      Ricardo Emerson     Consumer               1    793

[793 rows x 5 columns]

In [44]:
query = """
-- Create a common table expression to retrieve the customer_id, customer_name, segment and how many 
-- times the customer has purchased from the mall 

WITH customer_purchase AS (
	SELECT s.customer_id, 
           c.customer_name, 
           c.segment,
	       COUNT(*) AS purchase_count
	FROM sales s
	JOIN customers c
	ON s.customer_id = c.customer_id
	GROUP BY s.customer_id, c.customer_name, c.segment
	ORDER BY s.customer_id)

-- Number each customer by their customer segment
-- and by how many purchases they've made in descending order

SELECT *,
	   ROW_NUMBER() OVER (
    				PARTITION BY segment
				   	ORDER BY purchase_count DESC
                    ) AS Row_N
FROM customer_purchase
ORDER BY segment, purchase_count DESC;    
"""
pd.read_sql_query(query, conn)

    customer_id        customer_name      segment  purchase_count  Row_N
0      WB-21850        William Brown     Consumer              37      1
1      JL-15835             John Lee     Consumer              34      2
2      CK-12205  Chloris Kastensmidt     Consumer              32      3
3      SV-20365          Seth Vernon     Consumer              32      4
4      AP-10915       Arthur Prichep     Consumer              31      5
..          ...                  ...          ...             ...    ...
788    PC-19000        Pauline Chand  Home Office               3    144
789    PK-18910         Paul Knutson  Home Office               3    145
790    RS-19870           Roy Skaria  Home Office               3    146
791    EL-13735            Ed Ludwig  Home Office               2    147
792    PH-18790    Patricia Hirasaki  Home Office               2    148

[793 rows x 5 columns]

In [49]:
query = """
-- Retrieve all employees first name, department, salary and the salary after that employee

SELECT first_name, 
       department, 
       salary,
       LEAD(salary) OVER() AS next_employee_salary
FROM employees;
"""

pd.read_sql_query(query, conn)

    first_name        department  salary  next_employee_salary
0       Berrie            Sports  154864               56752.0
1      Aeriell             Tools   56752               95313.0
2       Sydney          Clothing   95313              119674.0
3        Avrom  Phones & Tablets  119674               55307.0
4       Feliks         Computers   55307              134501.0
..         ...               ...     ...                   ...
995   Gardiner            Garden  111859              120753.0
996    Rhianna            Beauty  120753              134058.0
997   Brandice  Phones & Tablets  134058               45679.0
998   Kingston             Music   45679               28726.0
999  Jacquelin             Music   28726                   NaN

[1000 rows x 4 columns]

In [55]:
query = """
-- Retrieve all employees first name, department, salary and the salary before that employee

SELECT first_name, 
       department, 
       salary,
       LAG(salary) OVER() AS previous_employee_salary
FROM employees
LIMIT 10;
"""

pd.read_sql_query(query, conn)

  first_name        department  salary  previous_employee_salary
0     Berrie            Sports  154864                       NaN
1    Aeriell             Tools   56752                  154864.0
2     Sydney          Clothing   95313                   56752.0
3      Avrom  Phones & Tablets  119674                   95313.0
4     Feliks         Computers   55307                  119674.0
5    Bethena            Sports  134501                   55307.0
6     Ardeen          Clothing   28995                  134501.0
7     Seline  Phones & Tablets  101066                   28995.0
8      Dayle         First Aid   82753                  101066.0
9    Redford          Clothing   72225                   82753.0

In [56]:
query = """
-- Retrieve all employees first name, department, salary and the salary after that employee in order of their salaries

SELECT first_name, 
       department, 
       salary,
       LEAD(salary) OVER(ORDER BY salary DESC) AS next_employee_salary
FROM employees
LIMIT 20;
"""
pd.read_sql_query(query, conn)

   first_name     department  salary  next_employee_salary
0     Jacklyn       Clothing  166976                166765
1     Carissa          Music  166765                166569
2       Riley        Camping  166569                166016
3      Lauren       Pharmacy  166016                165660
4        Lucy         Sports  165660                164588
5       Barby       Clothing  164588                164582
6          Ev        Grocery  164582                164470
7    Sherwynd         Sports  164470                164355
8     Michail  Device Repair  164355                164219
9    Hermione          Music  164219                164011
10        Rob      First Aid  164011                163933
11     Elvera       Vitamins  163933                163794
12    Hendrik        Jewelry  163794                163688
13       Zeke           Toys  163688                163512
14   Brandise      Computers  163512                163361
15      Bunny         Garden  163361                163239
16       Orsa      First Aid  163239                162926
17    Kerstin        Grocery  162926                162924
18      Paxon       Pharmacy  162924                162845
19     Orland         Beauty  162845                162522

In [59]:
query = """
-- Retrieve all employees first name, department, salary and the salary after that employee in order of their salaries

SELECT first_name, 
       department, 
       salary,
       LEAD(salary) OVER(ORDER BY salary DESC) AS next_employee_salary,
       (salary - LEAD(salary) OVER(ORDER BY salary DESC)) salary_diff 
FROM employees
LIMIT 20;
"""
pd.read_sql_query(query, conn)

   first_name     department  salary  next_employee_salary  salary_diff
0     Jacklyn       Clothing  166976                166765          211
1     Carissa          Music  166765                166569          196
2       Riley        Camping  166569                166016          553
3      Lauren       Pharmacy  166016                165660          356
4        Lucy         Sports  165660                164588         1072
5       Barby       Clothing  164588                164582            6
6          Ev        Grocery  164582                164470          112
7    Sherwynd         Sports  164470                164355          115
8     Michail  Device Repair  164355                164219          136
9    Hermione          Music  164219                164011          208
10        Rob      First Aid  164011                163933           78
11     Elvera       Vitamins  163933                163794          139
12    Hendrik        Jewelry  163794                163688          106
13       Zeke           Toys  163688                163512          176
14   Brandise      Computers  163512                163361          151
15      Bunny         Garden  163361                163239          122
16       Orsa      First Aid  163239                162926          313
17    Kerstin        Grocery  162926                162924            2
18      Paxon       Pharmacy  162924                162845           79
19     Orland         Beauty  162845                162522          323

In [60]:
query = """
-- Retrieve all employees first name, department, salary and the salary before that employee in order of their salaries in
-- descending order. Call the new column closest_higher_salary

SELECT first_name, 
       department, 
       salary,
       LAG(salary) OVER(ORDER BY salary DESC) closest_higher_salar
FROM employees;
"""

pd.read_sql_query(query, conn)

    first_name     department  salary  closest_higher_salar
0      Jacklyn       Clothing  166976                   NaN
1      Carissa          Music  166765              166976.0
2        Riley        Camping  166569              166765.0
3       Lauren       Pharmacy  166016              166569.0
4         Lucy         Sports  165660              166016.0
..         ...            ...     ...                   ...
995     Roarke  Device Repair   21023               21024.0
996    Marylin          Music   20776               21023.0
997      Roger  Device Repair   20664               20776.0
998      Addia        Grocery   20613               20664.0
999    Renault       Pharmacy   20542               20613.0

[1000 rows x 4 columns]

In [64]:
query = """
-- Retrieve all employees first name, department, salary and the salary after that employee for each department in descending order
-- of their salaries. Call the new column closest_lowest_salary 

SELECT first_name, 
       department, 
       salary,
LEAD(salary) OVER (PARTITION BY department
				   ORDER BY salary DESC) closest_lower_salary
FROM employees
LIMIT 40;
"""

pd.read_sql_query(query, conn)

    first_name  department  salary  closest_lower_salary
0         Mill  Automotive  162522              160783.0
1        Irita  Automotive  160783              160039.0
2       Tammie  Automotive  160039              157260.0
3       Roslyn  Automotive  157260              152141.0
4       Betsey  Automotive  152141              150821.0
5    Cherianne  Automotive  150821              146522.0
6      Chrissy  Automotive  146522              144511.0
7        Poppy  Automotive  144511              144146.0
8           Cy  Automotive  144146              137393.0
9      Jilleen  Automotive  137393              137094.0
10     Merlina  Automotive  137094              130995.0
11      Charis  Automotive  130995              126983.0
12      Stormy  Automotive  126983              125305.0
13      Noelyn  Automotive  125305              123828.0
14       Cybil  Automotive  123828              119959.0
15     Lorelle  Automotive  119959              115973.0
16   Maryellen  Automotive  115973              111775.0
17     Ladonna  Automotive  111775              111359.0
18        Ivie  Automotive  111359              106517.0
19      Abbott  Automotive  106517              106046.0
20         Doe  Automotive  106046              103570.0
21       Vanda  Automotive  103570               95492.0
22  Clementina  Automotive   95492               86929.0
23    Jessalyn  Automotive   86929               75978.0
24    Lauretta  Automotive   75978               69379.0
25   Archibold  Automotive   69379               60089.0
26      Katlin  Automotive   60089               56095.0
27    Sterling  Automotive   56095               51989.0
28         Way  Automotive   51989               47591.0
29        Tabb  Automotive   47591               44641.0
30     Berkley  Automotive   44641               29752.0
31      Laurie  Automotive   29752                   NaN
32      Orland      Beauty  162845              162169.0
33       Urban      Beauty  162169              154018.0
34      Baxter      Beauty  154018              151926.0
35       Neddy      Beauty  151926              145225.0
36      Garald      Beauty  145225              144955.0
37       Aguie      Beauty  144955              141315.0
38     Carlyle      Beauty  141315              138181.0
39      Murray      Beauty  138181              137691.0

In [65]:
query = """
SELECT first_name, 
       department, 
       salary,
       LEAD(salary, 1) OVER (ORDER BY salary DESC) closest_salary,
       LEAD(salary, 2) OVER (ORDER BY salary DESC) next_closest_salary
FROM employees
WHERE department = 'Clothing';
"""
pd.read_sql_query(query, conn)

    first_name department  salary  closest_salary  next_closest_salary
0      Jacklyn   Clothing  166976        164588.0             160417.0
1        Barby   Clothing  164588        160417.0             157392.0
2      Manfred   Clothing  160417        157392.0             150887.0
3     Faustine   Clothing  157392        150887.0             141256.0
4       Hester   Clothing  150887        141256.0             132264.0
5   Cirstoforo   Clothing  141256        132264.0             128327.0
6     Maryanna   Clothing  132264        128327.0             126305.0
7       Kippie   Clothing  128327        126305.0             124949.0
8     Rochette   Clothing  126305        124949.0             116966.0
9     Bernardo   Clothing  124949        116966.0             113213.0
10        Fina   Clothing  116966        113213.0             104667.0
11      Karlis   Clothing  113213        104667.0              97156.0
12     Chantal   Clothing  104667         97156.0              95313.0
13      Verney   Clothing   97156         95313.0              92839.0
14      Sydney   Clothing   95313         92839.0              89961.0
15   Stanfield   Clothing   92839         89961.0              89695.0
16      Collie   Clothing   89961         89695.0              88652.0
17   Meredithe   Clothing   89695         88652.0              88534.0
18       Geoff   Clothing   88652         88534.0              88291.0
19    Mortimer   Clothing   88534         88291.0              87108.0
20       Camey   Clothing   88291         87108.0              86352.0
21      Lawton   Clothing   87108         86352.0              86194.0
22        Port   Clothing   86352         86194.0              77589.0
23      Weylin   Clothing   86194         77589.0              77259.0
24     Darnall   Clothing   77589         77259.0              75340.0
25    Birgitta   Clothing   77259         75340.0              72225.0
26       Iosep   Clothing   75340         72225.0              68190.0
27     Redford   Clothing   72225         68190.0              67857.0
28       Becka   Clothing   68190         67857.0              65336.0
29       Asher   Clothing   67857         65336.0              61632.0
30         Bev   Clothing   65336         61632.0              61614.0
31      Dorree   Clothing   61632         61614.0              57843.0
32       Glynn   Clothing   61614         57843.0              57375.0
33         Job   Clothing   57843         57375.0              51682.0
34    Kariotta   Clothing   57375         51682.0              50835.0
35     Kristin   Clothing   51682         50835.0              50300.0
36       Caryl   Clothing   50835         50300.0              48814.0
37      Elvira   Clothing   50300         48814.0              48192.0
38       Lindy   Clothing   48814         48192.0              48107.0
39        Dunc   Clothing   48192         48107.0              45892.0
40     Gianina   Clothing   48107         45892.0              44967.0
41      Phoebe   Clothing   45892         44967.0              39200.0
42     Filippa   Clothing   44967         39200.0              36023.0
43      Eloisa   Clothing   39200         36023.0              35593.0
44      Ludwig   Clothing   36023         35593.0              31792.0
45    Benyamin   Clothing   35593         31792.0              31785.0
46      Eudora   Clothing   31792         31785.0              28995.0
47      Reidar   Clothing   31785         28995.0                  NaN
48      Ardeen   Clothing   28995             NaN                  NaN

In [90]:
query = """
-- Retrieve the first_name, last_name, department, and hire_date of all employees. 
-- Add a new column called first_emp_date that returns the hire date of the first hired employee.
-- Find the difference between the hire date of the first employee hired and every other employees

SELECT first_name,
       last_name,
       department,
       hire_date,
       FIRST_VALUE(hire_date) OVER(ORDER BY hire_date) AS first_emp_date,
       CAST(julianday(hire_date) - julianday(FIRST_VALUE(hire_date) OVER(ORDER BY hire_date)) AS INT) AS days_difference
FROM employees;
"""

pd.read_sql_query(query, conn)

,first_name,last_name,department,hire_date,first_emp_date,days_difference
0,Norbie,Bleasdille,First Aid,2003-01-01,2003-01-01,0
1,Cassandra,Hoston,Beauty,2003-01-01,2003-01-01,0
2,Rora,Brumfitt,Children Clothing,2003-01-12,2003-01-01,11
3,Feliks,Morffew,Computers,2003-01-14,2003-01-01,13
4,Cecilius,Cottey,Vitamins,2003-01-20,2003-01-01,19
...,...,...,...,...,...,...
995,Eloisa,Eeles,Clothing,2016-12-02,2003-01-01,5084
996,Edik,Wardhough,Tools,2016-12-11,2003-01-01,5093
997,Roxie,Revance,Phones & Tablets,2016-12-16,2003-01-01,5098
998,Cherianne,Oxnam,Automotive,2016-12-18,2003-01-01,5100
999,Barby,Daniell,Clothing,2016-12-26,2003-01-01,5108

In [91]:
query = """
-- Exercise 7.1: Partition by department
SELECT first_name, 
       last_name, 
       department, 
       hire_date,
FIRST_VALUE(hire_date) OVER (
            PARTITION BY department
			ORDER BY hire_date) AS first_emp_date
FROM employees;
"""

pd.read_sql_query(query, conn)

     first_name   last_name  department   hire_date first_emp_date
0     Maryellen   Westnedge  Automotive  2003-04-19     2003-04-19
1     Archibold       Deely  Automotive  2003-04-26     2003-04-19
2          Tabb  Huddleston  Automotive  2003-05-02     2003-04-19
3        Abbott      Mundow  Automotive  2003-06-05     2003-04-19
4       Ladonna      McCrow  Automotive  2003-08-10     2003-04-19
..          ...         ...         ...         ...            ...
995  Bartholemy  Crudginton    Vitamins  2015-11-08     2003-01-20
996       Ivett    Brierley    Vitamins  2016-03-18     2003-01-20
997       Nadia      Alonso    Vitamins  2016-03-25     2003-01-20
998      Elvera     Tinline    Vitamins  2016-07-17     2003-01-20
999      Buckie   Jodrellec    Vitamins  2016-10-10     2003-01-20

[1000 rows x 5 columns]

In [95]:
query = """
-- Exercise 7.2: Find the difference between the hire date of the 
-- first employee hired and every other employees partitioned by department

SELECT *, CAST(julianday(a.hire_date) - julianday(a.first_emp_date) AS INT) AS days_diff
FROM (
    SELECT first_name, 
            last_name, 
            department, 
            hire_date,
            FIRST_VALUE(hire_date) OVER (
                PARTITION BY department
			    ORDER BY hire_date) AS first_emp_date
    FROM employees) a
ORDER BY department;
"""

pd.read_sql_query(query, conn)

     first_name   last_name  department   hire_date first_emp_date  days_diff
0     Maryellen   Westnedge  Automotive  2003-04-19     2003-04-19          0
1     Archibold       Deely  Automotive  2003-04-26     2003-04-19          7
2          Tabb  Huddleston  Automotive  2003-05-02     2003-04-19         13
3        Abbott      Mundow  Automotive  2003-06-05     2003-04-19         47
4       Ladonna      McCrow  Automotive  2003-08-10     2003-04-19        113
..          ...         ...         ...         ...            ...        ...
995  Bartholemy  Crudginton    Vitamins  2015-11-08     2003-01-20       4675
996       Ivett    Brierley    Vitamins  2016-03-18     2003-01-20       4806
997       Nadia      Alonso    Vitamins  2016-03-25     2003-01-20       4813
998      Elvera     Tinline    Vitamins  2016-07-17     2003-01-20       4927
999      Buckie   Jodrellec    Vitamins  2016-10-10     2003-01-20       5012

[1000 rows x 6 columns]

In [99]:
# To find the number of months between the 2 dates

query = """
SELECT *, (strftime('%Y', a.hire_date) - strftime('%Y', a.first_emp_date)) * 12 + 
                        (strftime('%m', a.hire_date) - strftime('%m', a.first_emp_date)) AS months_diff
FROM (
    SELECT first_name, 
            last_name, 
            department, 
            hire_date,
            FIRST_VALUE(hire_date) OVER (
                PARTITION BY department
			    ORDER BY hire_date) AS first_emp_date
    FROM employees) a
ORDER BY department;
"""

pd.read_sql_query(query, conn)

,first_name,last_name,department,hire_date,first_emp_date,months_diff
0,Maryellen,Westnedge,Automotive,2003-04-19,2003-04-19,0
1,Archibold,Deely,Automotive,2003-04-26,2003-04-19,0
2,Tabb,Huddleston,Automotive,2003-05-02,2003-04-19,1
3,Abbott,Mundow,Automotive,2003-06-05,2003-04-19,2
4,Ladonna,McCrow,Automotive,2003-08-10,2003-04-19,4
...,...,...,...,...,...,...
995,Bartholemy,Crudginton,Vitamins,2015-11-08,2003-01-20,154
996,Ivett,Brierley,Vitamins,2016-03-18,2003-01-20,158
997,Nadia,Alonso,Vitamins,2016-03-25,2003-01-20,158
998,Elvera,Tinline,Vitamins,2016-07-17,2003-01-20,162
999,Buckie,Jodrellec,Vitamins,2016-10-10,2003-01-20,165

In [103]:
query = """
-- Exercise 8.1: Return the first salary for different departments. Order by the salary in descending order

SELECT *, 
	   (first_salary - salary) AS salary_diff
FROM (
		SELECT first_name, 
	   	email, 
       	department, 
       	salary,
	   	FIRST_VALUE(salary) OVER(PARTITION BY department
						 ORDER BY salary DESC) first_salary
FROM employees) a
LIMIT 20;
"""

pd.read_sql_query(query, conn)

,first_name,email,department,salary,first_salary,salary_diff
0,Mill,None,Automotive,162522,162522,0
1,Irita,istarie2h@answers.com,Automotive,160783,162522,1739
2,Tammie,None,Automotive,160039,162522,2483
3,Roslyn,rguiu3h@com.com,Automotive,157260,162522,5262
4,Betsey,breedshawc5@phoca.cz,Automotive,152141,162522,10381
5,Cherianne,None,Automotive,150821,162522,11701
6,Chrissy,cappletonlq@census.gov,Automotive,146522,162522,16000
7,Poppy,plinesn7@gmpg.org,Automotive,144511,162522,18011
8,Cy,cmenceft@icq.com,Automotive,144146,162522,18376
9,Jilleen,None,Automotive,137393,162522,25129
10,Merlina,None,Automotive,137094,162522,25428
11,Charis,cbradbornejp@scribd.com,Automotive,130995,162522,31527
12,Stormy,None,Automotive,126983,162522,35539
13,Noelyn,ndemarchiiy@slashdot.org,Automotive,125305,162522,37217
14,Cybil,cperezea@a8.net,Automotive,123828,162522,38694
15,Lorelle,lkelberman7l@wired.com,Automotive,119959,162522,42563
16,Maryellen,mwestnedgepq@guardian.co.uk,Automotive,115973,162522,46549
17,Ladonna,lmccrow8g@nhs.uk,Automotive,111775,162522,50747
18,Ivie,iaubreykx@google.es,Automotive,111359,162522,51163
19,Abbott,amundowhz@prlog.org,Automotive,106517,162522,56005

In [ ]:
# 2nd way - using MAX as a window function
query = """
SELECT first_name, 
       email, 
       department, 
       salary,
       MAX(salary) OVER(PARTITION BY department
				 ORDER BY salary DESC) first_salary
FROM employees;
"""

pd.read_sql_query(query, conn)

     first_name                        email  department  salary  first_salary
0          Mill                         None  Automotive  162522        162522
1         Irita        istarie2h@answers.com  Automotive  160783        162522
2        Tammie                         None  Automotive  160039        162522
3        Roslyn              rguiu3h@com.com  Automotive  157260        162522
4        Betsey         breedshawc5@phoca.cz  Automotive  152141        162522
..          ...                          ...         ...     ...           ...
995      Buckie  bjodrellec7z@vistaprint.com    Vitamins   30289        163933
996  Bartholemy     bcrudgintone1@dion.ne.jp    Vitamins   25238        163933
997     Maridel          mwhellans9i@hud.gov    Vitamins   24884        163933
998       Ashia                         None    Vitamins   22190        163933
999         Ame            apateman97@ca.gov    Vitamins   21931        163933

[1000 rows x 5 columns]

In [105]:
query = """
-- Exercise 8.2: Return the first salary for different departments. Order by the first_name in ascending order

SELECT first_name, 
       email, 
       department, 
       salary,
       FIRST_VALUE(salary) OVER(PARTITION BY department
						 ORDER BY first_name) AS first_salary
FROM employees
LIMIT 40;
"""

pd.read_sql_query(query, conn)

    first_name                        email  department  salary  first_salary
0       Abbott          amundowhz@prlog.org  Automotive  106517        106517
1    Archibold             adeelynb@fda.gov  Automotive   69379        106517
2      Berkley                         None  Automotive   44641        106517
3       Betsey         breedshawc5@phoca.cz  Automotive  152141        106517
4       Charis      cbradbornejp@scribd.com  Automotive  130995        106517
5    Cherianne                         None  Automotive  150821        106517
6      Chrissy       cappletonlq@census.gov  Automotive  146522        106517
7   Clementina    cfrankcombec1@foxnews.com  Automotive   95492        106517
8           Cy             cmenceft@icq.com  Automotive  144146        106517
9        Cybil              cperezea@a8.net  Automotive  123828        106517
10         Doe      dlarkworthyao@amazon.de  Automotive  106046        106517
11       Irita        istarie2h@answers.com  Automotive  160783        106517
12        Ivie          iaubreykx@google.es  Automotive  111359        106517
13    Jessalyn       jhorleycn@bluehost.com  Automotive   86929        106517
14     Jilleen                         None  Automotive  137393        106517
15      Katlin          kbemroseg1@webs.com  Automotive   60089        106517
16     Ladonna             lmccrow8g@nhs.uk  Automotive  111775        106517
17    Lauretta      lroundsa6@wordpress.org  Automotive   75978        106517
18      Laurie    linfantinonf@china.com.cn  Automotive   29752        106517
19     Lorelle       lkelberman7l@wired.com  Automotive  119959        106517
20   Maryellen  mwestnedgepq@guardian.co.uk  Automotive  115973        106517
21     Merlina                         None  Automotive  137094        106517
22        Mill                         None  Automotive  162522        106517
23      Noelyn     ndemarchiiy@slashdot.org  Automotive  125305        106517
24       Poppy            plinesn7@gmpg.org  Automotive  144511        106517
25      Roslyn              rguiu3h@com.com  Automotive  157260        106517
26    Sterling      spagen6w@privacy.gov.au  Automotive   56095        106517
27      Stormy                         None  Automotive  126983        106517
28        Tabb    thuddlestonrf@yahoo.co.jp  Automotive   47591        106517
29      Tammie                         None  Automotive  160039        106517
30       Vanda          vmarwickm@upenn.edu  Automotive  103570        106517
31         Way        wkochlinm6@meetup.com  Automotive   51989        106517
32       Aguie            aepslyn2@xing.com      Beauty  144955        144955
33       Alvin          amcmullenpo@icio.us      Beauty   69999        144955
34      Baxter                         None      Beauty  154018        144955
35        Benn     bdudleyt@dailymail.co.uk      Beauty   67800        144955
36     Carlyle        cjosipovitzqn@npr.org      Beauty  141315        144955
37   Cassandra           choston8b@jugem.jp      Beauty  106936        144955
38    Claribel          ckettoweh@bbc.co.uk      Beauty   22348        144955
39     De witt                         None      Beauty   74511        144955

In [107]:
query = """
-- Now return the fifth salary for different departments
-- Order by the first_name in ascending order

SELECT first_name, 
       email, 
       department, 
       salary,
       NTH_VALUE(salary, 5) OVER(PARTITION BY department
						 ORDER BY first_name) AS fifth_salary
FROM employees
LIMIT 40;
"""

pd.read_sql_query(query, conn)

    first_name                        email  department  salary  fifth_salary
0       Abbott          amundowhz@prlog.org  Automotive  106517           NaN
1    Archibold             adeelynb@fda.gov  Automotive   69379           NaN
2      Berkley                         None  Automotive   44641           NaN
3       Betsey         breedshawc5@phoca.cz  Automotive  152141           NaN
4       Charis      cbradbornejp@scribd.com  Automotive  130995      130995.0
5    Cherianne                         None  Automotive  150821      130995.0
6      Chrissy       cappletonlq@census.gov  Automotive  146522      130995.0
7   Clementina    cfrankcombec1@foxnews.com  Automotive   95492      130995.0
8           Cy             cmenceft@icq.com  Automotive  144146      130995.0
9        Cybil              cperezea@a8.net  Automotive  123828      130995.0
10         Doe      dlarkworthyao@amazon.de  Automotive  106046      130995.0
11       Irita        istarie2h@answers.com  Automotive  160783      130995.0
12        Ivie          iaubreykx@google.es  Automotive  111359      130995.0
13    Jessalyn       jhorleycn@bluehost.com  Automotive   86929      130995.0
14     Jilleen                         None  Automotive  137393      130995.0
15      Katlin          kbemroseg1@webs.com  Automotive   60089      130995.0
16     Ladonna             lmccrow8g@nhs.uk  Automotive  111775      130995.0
17    Lauretta      lroundsa6@wordpress.org  Automotive   75978      130995.0
18      Laurie    linfantinonf@china.com.cn  Automotive   29752      130995.0
19     Lorelle       lkelberman7l@wired.com  Automotive  119959      130995.0
20   Maryellen  mwestnedgepq@guardian.co.uk  Automotive  115973      130995.0
21     Merlina                         None  Automotive  137094      130995.0
22        Mill                         None  Automotive  162522      130995.0
23      Noelyn     ndemarchiiy@slashdot.org  Automotive  125305      130995.0
24       Poppy            plinesn7@gmpg.org  Automotive  144511      130995.0
25      Roslyn              rguiu3h@com.com  Automotive  157260      130995.0
26    Sterling      spagen6w@privacy.gov.au  Automotive   56095      130995.0
27      Stormy                         None  Automotive  126983      130995.0
28        Tabb    thuddlestonrf@yahoo.co.jp  Automotive   47591      130995.0
29      Tammie                         None  Automotive  160039      130995.0
30       Vanda          vmarwickm@upenn.edu  Automotive  103570      130995.0
31         Way        wkochlinm6@meetup.com  Automotive   51989      130995.0
32       Aguie            aepslyn2@xing.com      Beauty  144955           NaN
33       Alvin          amcmullenpo@icio.us      Beauty   69999           NaN
34      Baxter                         None      Beauty  154018           NaN
35        Benn     bdudleyt@dailymail.co.uk      Beauty   67800           NaN
36     Carlyle        cjosipovitzqn@npr.org      Beauty  141315      141315.0
37   Cassandra           choston8b@jugem.jp      Beauty  106936      141315.0
38    Claribel          ckettoweh@bbc.co.uk      Beauty   22348      141315.0
39     De witt                         None      Beauty   74511      141315.0