In [3]:
import pandas as pd
import sqlite3

conn = sqlite3.connect('data/raw/project-db.db')

In [4]:
query = """
SELECT name FROM sqlite_master WHERE type='table';
"""
pd.read_sql_query(query, conn)    # List all tables in the database

          name
0  departments
1      regions
2    employees
3    customers
4        sales

**Rank, Dense_Rank, and Row_Number Window Functions**

In [ ]:
# Retrieve a list of employee_id, first_name, hire_date, and department of all employees ordered by the hire date
query = """
SELECT employee_id,
       first_name,
       hire_date,
       department,
       -- Use DENSE_RANK() to return consecutive integers regardless you ties or not. As shown, there is a tie in the 1st 2 hire dates, and the 
       -- 3rd rank of the hire date is incremented to 2, not to 3 like the RANK() Function. So for RANK() Function, you would get 1,1,3. 
       -- For DENSE_RANK(), you get 1,1,2
       DENSE_RANK() OVER(ORDER BY hire_date) AS rank
FROM employees
LIMIT 20;
"""

pd.read_sql_query(query, conn)

    employee_id first_name   hire_date         department  rank
0           271     Norbie  2003-01-01          First Aid     1
1           300  Cassandra  2003-01-01             Beauty     1
2            79       Rora  2003-01-12  Children Clothing     2
3             5     Feliks  2003-01-14          Computers     3
4           739   Cecilius  2003-01-20           Vitamins     4
5           488   Eugenius  2003-01-26               Toys     5
6            75   Fiorenze  2003-02-17   Phones & Tablets     6
7            83     Elnora  2003-02-22          First Aid     7
8           744    Chelsey  2003-02-24          First Aid     8
9           814   Dorothea  2003-02-27            Grocery     9
10          194    Yardley  2003-02-28            Jewelry    10
11            9      Dayle  2003-03-01          First Aid    11
12          486       Bear  2003-03-02              Decor    12
13          766     Nonnah  2003-03-08              Music    13
14          625      Jamie  2003-03-13          Cosmetics    14
15          291       Arvy  2003-03-16             Garden    15
16           38       Edna  2003-04-09  Children Clothing    16
17          942       Alis  2003-04-09              Books    16
18          927  Maryellen  2003-04-19         Automotive    17
19          870     Dorene  2003-04-23              Decor    18

In [ ]:
# Retrieve the employee_id, first_name, hire_date of employees for different departments
query = """
SELECT employee_id,
       first_name,
       hire_date,
       department,
       -- Now, partition by department, to get the info of employees per department numbered and ordered by hire date
       ROW_NUMBER() OVER(
            PARTITION BY department
            ORDER BY hire_date) AS Row_N
FROM employees
LIMIT 40;
"""

pd.read_sql_query(query, conn)

    employee_id  first_name   hire_date  department  Row_N
0           927   Maryellen  2003-04-19  Automotive      1
1           840   Archibold  2003-04-26  Automotive      2
2           988        Tabb  2003-05-02  Automotive      3
3           648      Abbott  2003-06-05  Automotive      4
4           305     Ladonna  2003-08-10  Automotive      5
5           126      Roslyn  2003-08-11  Automotive      6
6           274     Lorelle  2004-01-27  Automotive      7
7           515       Cybil  2004-04-01  Automotive      8
8           249    Sterling  2004-09-02  Automotive      9
9           456    Jessalyn  2004-10-03  Automotive     10
10           90       Irita  2004-10-15  Automotive     11
11          799         Way  2006-07-15  Automotive     12
12          844      Laurie  2007-05-31  Automotive     13
13          843     Berkley  2007-06-11  Automotive     14
14          367    Lauretta  2007-12-14  Automotive     15
15          951     Merlina  2009-02-16  Automotive     16
16          754        Ivie  2010-04-04  Automotive     17
17          836       Poppy  2010-07-27  Automotive     18
18          495        Mill  2011-01-08  Automotive     19
19          578      Katlin  2011-05-21  Automotive     20
20          247      Tammie  2011-12-08  Automotive     21
21          438      Betsey  2012-02-10  Automotive     22
22           97     Jilleen  2013-04-20  Automotive     23
23           23       Vanda  2014-02-06  Automotive     24
24          783     Chrissy  2014-02-27  Automotive     25
25          683      Noelyn  2014-05-28  Automotive     26
26          385         Doe  2014-10-14  Automotive     27
27          394      Stormy  2015-07-28  Automotive     28
28          710      Charis  2015-08-14  Automotive     29
29          570          Cy  2016-01-18  Automotive     30
30          434  Clementina  2016-09-04  Automotive     31
31          460   Cherianne  2016-12-18  Automotive     32
32          300   Cassandra  2003-01-01      Beauty      1
33          204  Willabella  2003-08-18      Beauty      2
34           35    Olenolin  2004-09-29      Beauty      3
35          664       Lukas  2004-11-03      Beauty      4
36          997     Rhianna  2005-04-07      Beauty      5
37          161      Kathye  2005-10-09      Beauty      6
38          875    Eldredge  2006-04-30      Beauty      7
39          353      Garrot  2006-07-10      Beauty      8

In [24]:
query = """ 
-- Retrieve the hire_date. Return details of employees hired on or before 31st Dec, 2005 and are in First Aid, Movies and Computers departments

SELECT first_name, 
       email, 
       department, 
       salary,
       hire_date,
       RANK() OVER (
            PARTITION BY department
            ORDER BY salary DESC) AS ranked_salary
FROM employees
WHERE hire_date <= '2005-12-31' AND
      department IN ('First Aid', 'Movies', 'Computers');
"""

pd.read_sql_query(query, conn)

,first_name,email,department,salary,hire_date,ranked_salary
0,Parnell,pdavidoff8i@zimbio.com,Computers,155000,2004-03-29,1
1,Webb,NaN,Computers,152504,2005-10-13,2
2,Javier,jrosendale98@ca.gov,Computers,87199,2003-11-12,3
3,Retha,rdebneyak@indiegogo.com,Computers,74771,2004-06-29,4
4,Feliks,fmorffew4@a8.net,Computers,55307,2003-01-14,5
5,Kimberley,NaN,Computers,49788,2004-01-08,6
6,Levi,NaN,Computers,35076,2003-10-21,7
7,Iver,NaN,Computers,21626,2004-12-30,8
8,Orsa,otournel5@webmd.com,First Aid,163239,2005-07-19,1
9,Stacee,spawellek7e@fotki.com,First Aid,136707,2004-04-21,2
10,Fonzie,NaN,First Aid,134991,2005-11-25,3
11,Kalie,kdowthwaite3u@technorati.com,First Aid,132796,2003-11-24,4
12,Leland,lreichartzpz@webeden.co.uk,First Aid,131935,2005-06-04,5
13,Joseito,jbaumertl8@dot.gov,First Aid,104018,2004-09-17,6
14,Tracey,tbuncombehw@yahoo.com,First Aid,96845,2005-12-03,7
15,Dayle,dtrail8@tamu.edu,First Aid,82753,2003-03-01,8
16,Norbie,nbleasdille7i@foxnews.com,First Aid,82215,2003-01-01,9
17,Byrle,NaN,First Aid,70260,2005-03-18,10
18,Daryl,dseedull94@irs.gov,First Aid,62561,2004-10-14,11
19,Chelsey,cvedikhovkn@histats.com,First Aid,57309,2003-02-24,12
20,Verina,vfurzeyid@zdnet.com,First Aid,53924,2005-06-03,13
21,Charin,cheinicke89@arizona.edu,First Aid,42847,2005-12-30,14
22,Elnora,ebabin2a@foxnews.com,First Aid,34355,2003-02-22,15
23,Lois,lcianelli74@baidu.com,First Aid,29539,2003-11-27,16
24,Rafaello,NaN,Movies,159463,2005-01-11,1
25,Kerry,ktollerfieldio@wordpress.org,Movies,156513,2004-02-20,2
26,Olivie,oissett3n@purevolume.com,Movies,155316,2004-05-31,3
27,Cobbie,cleidennk@archive.org,Movies,155158,2005-09-04,4
28,Granny,NaN,Movies,125798,2003-05-13,5
29,Ewart,ecarrenfc@google.ru,Movies,112238,2004-03-19,6
30,Elbertina,ekidderg0@eepurl.com,Movies,111253,2003-07-22,7
31,Anatola,adaultonbx@ftc.gov,Movies,92703,2003-12-14,8
32,Roarke,rsully31@army.mil,Movies,86223,2004-10-26,9
33,Darell,dleyburnec@xinhuanet.com,Movies,70928,2004-03-07,10
34,Brier,bfrillo6@twitpic.com,Movies,48719,2004-07-03,11
35,Jacqui,NaN,Movies,45570,2003-07-05,12
36,Christan,cmarikhindn@mapy.cz,Movies,25840,2004-01-12,13

In [25]:
query = """
-- This returns how many employees are in each department
SELECT department, 
       COUNT(*) dept_count
FROM employees
GROUP BY department
ORDER BY dept_count DESC;
"""

pd.read_sql_query(query, conn)

           department  dept_count
0           First Aid          58
1              Movies          56
2       Device Repair          51
3            Clothing          49
4                Toys          47
5           Computers          47
6   Children Clothing          47
7              Beauty          45
8           Furniture          43
9             Jewelry          41
10             Garden          41
11              Tools          39
12              Decor          39
13           Pharmacy          38
14           Vitamins          37
15              Books          37
16              Games          36
17            Camping          36
18   Phones & Tablets          35
19             Sports          34
20          Cosmetics          34
21         Automotive          32
22              Music          29
23            Grocery          28
24        Maintenance           8
25           Plumbing           7
26           Security           6

In [26]:
## Return the fifth ranked salary for each department
query = """
WITH ranked_salary_cte AS (
    SELECT first_name, 
            email, 
            department, 
            salary,
            hire_date,
            RANK() OVER (
                PARTITION BY department
                ORDER BY salary DESC) AS ranked_salary
FROM employees
WHERE hire_date <= '2005-12-31' AND
      department IN ('First Aid', 'Movies', 'Computers'))

SELECT * FROM ranked_salary_cte
WHERE ranked_salary = 5;
"""

pd.read_sql_query(query, conn)

,first_name,email,department,salary,hire_date,ranked_salary
0,Feliks,fmorffew4@a8.net,Computers,55307,2003-01-14,5
1,Leland,lreichartzpz@webeden.co.uk,First Aid,131935,2005-06-04,5
2,Granny,NaN,Movies,125798,2003-05-13,5

In [29]:
# 2nd way using subqueries
query = """
SELECT *
FROM (SELECT first_name, 
             email, 
             department,
             salary,
             DENSE_RANK() OVER (
                     PARTITION BY department
                     ORDER BY salary DESC) AS ranked_salary
       FROM employees
       ) AS sub
WHERE ranked_salary = 5;
"""
pd.read_sql_query(query, conn)

,first_name,email,department,salary,ranked_salary
0,Betsey,breedshawc5@phoca.cz,Automotive,152141,5
1,Garald,NaN,Beauty,145225,5
2,Christine,chessing2y@dailymail.co.uk,Books,149864,5
3,Kevin,kschubart9v@dailymotion.com,Camping,154856,5
4,Nicolis,nvigersdo@t.co,Children Clothing,137567,5
5,Hester,hseakin27@netlog.com,Clothing,150887,5
6,Laryssa,lmumns@shinystat.com,Computers,152831,5
7,Gabriel,gwidocks5i@acquirethisname.com,Cosmetics,154376,5
8,Gorden,NaN,Decor,146577,5
9,Sebastian,slefeuvre6d@abc.net.au,Device Repair,157861,5
10,Lanie,lzamoraph@unicef.org,First Aid,151539,5
11,Caralie,NaN,Furniture,155980,5
12,Ibby,NaN,Games,132891,5
13,Anders,aaronovitzjv@furl.net,Garden,152439,5
14,Georgianne,NaN,Grocery,153826,5
15,Albert,amcclementsk0@imageshack.us,Jewelry,143432,5
16,Keenan,kgerranls@disqus.com,Maintenance,47734,5
17,Cobbie,cleidennk@archive.org,Movies,155158,5
18,Alisa,aallender5y@delicious.com,Music,161283,5
19,Benjamen,bdiscombeq1@youtube.com,Pharmacy,159011,5
20,Fiona,fdellatorrequ@soundcloud.com,Phones & Tablets,149004,5
21,Rosalia,rbeltonh6@kickstarter.com,Plumbing,72546,5
22,Gianni,ggoodshipim@miibeian.gov.cn,Security,38963,5
23,Stanley,NaN,Sports,151814,5
24,Kyrstin,NaN,Tools,126942,5
25,Eugenius,esiegedj@gizmodo.com,Toys,152118,5
26,Xever,xbagottnz@soundcloud.com,Vitamins,145879,5

In [34]:
# Create a CTE
query = """
WITH purchase_count AS (
SELECT Customer_ID, COUNT(Sales) as purchase_N 
FROM sales
GROUP BY Customer_ID)

-- Difference between ROW_NUMBER(), RANK(), and DENSE_RANK()
SELECT *,
       ROW_NUMBER() OVER(ORDER BY purchase_N DESC) AS Row_N,
       RANK() OVER(ORDER BY purchase_N DESC) AS rank_N,
       DENSE_RANK() OVER(ORDER BY purchase_N DESC) AS dense_rank_N
FROM purchase_count
LIMIT 40;
"""
pd.read_sql_query(query, conn)

   Customer_ID  purchase_N  Row_N  rank_N  dense_rank_N
0     WB-21850          37      1       1             1
1     JL-15835          34      2       2             2
2     MA-17560          34      3       2             2
3     PP-18955          34      4       2             2
4     CK-12205          32      5       5             3
5     EH-13765          32      6       5             3
6     JD-15895          32      7       5             3
7     SV-20365          32      8       5             3
8     AP-10915          31      9       9             4
9     EP-13915          31     10       9             4
10    ZC-21910          31     11       9             4
11    LC-16870          30     12      12             5
12    BM-11650          29     13      13             6
13    Dp-13240          29     14      13             6
14    GT-14710          29     15      13             6
15    KL-16645          29     16      13             6
16    SH-19975          29     17      13             6
17    CL-12565          28     18      18             7
18    CS-12250          28     19      18             7
19    KD-16495          28     20      18             7
20    KM-16720          28     21      18             7
21    XP-21865          28     22      18             7
22    BF-11170          27     23      23             8
23    DK-12835          27     24      23             8
24    CB-12025          26     25      25             9
25    LA-16780          26     26      25             9
26    NS-18640          26     27      25             9
27    PG-18820          26     28      25             9
28    SC-20725          26     29      25             9
29    AS-10090          25     30      30            10
30    CK-12595          25     31      30            10
31    EA-14035          25     32      30            10
32    PK-19075          25     33      30            10
33    RP-19390          25     34      30            10
34    SV-20785          25     35      30            10
35    BH-11710          24     36      36            11
36    DR-12880          24     37      36            11
37    GG-14650          24     38      36            11
38    JA-15970          24     39      36            11
39    LB-16795          24     40      36            11

**NTILE Window Function**

NTILE() is used to break or page the result set into groups!

In [ ]:
# Group the employees table into five groups based on the order of their salaries
query = """
SELECT first_name, 
       department, 
       salary,
       NTILE(5) OVER(ORDER BY salary DESC) AS grouped_salaries
FROM employees;
"""
pd.read_sql_query(query, conn)  # Each group has 200 records

    first_name     department  salary  grouped_salaries
0      Jacklyn       Clothing  166976                 1
1      Carissa          Music  166765                 1
2        Riley        Camping  166569                 1
3       Lauren       Pharmacy  166016                 1
4         Lucy         Sports  165660                 1
..         ...            ...     ...               ...
995     Roarke  Device Repair   21023                 5
996    Marylin          Music   20776                 5
997      Roger  Device Repair   20664                 5
998      Addia        Grocery   20613                 5
999    Renault       Pharmacy   20542                 5

[1000 rows x 4 columns]

In [ ]:
# Now, group the employees table into five groups for each department based on the order of their salaries
query = """
SELECT first_name, 
       department, 
       salary,
       NTILE(5) OVER(
            PARTITION BY department
            ORDER BY salary DESC) AS grouped_salaries
FROM employees
LIMIT 40;
"""
pd.read_sql_query(query, conn)  # Each department is split into 5 groups

    first_name  department  salary  grouped_salaries
0         Mill  Automotive  162522                 1
1        Irita  Automotive  160783                 1
2       Tammie  Automotive  160039                 1
3       Roslyn  Automotive  157260                 1
4       Betsey  Automotive  152141                 1
5    Cherianne  Automotive  150821                 1
6      Chrissy  Automotive  146522                 1
7        Poppy  Automotive  144511                 2
8           Cy  Automotive  144146                 2
9      Jilleen  Automotive  137393                 2
10     Merlina  Automotive  137094                 2
11      Charis  Automotive  130995                 2
12      Stormy  Automotive  126983                 2
13      Noelyn  Automotive  125305                 2
14       Cybil  Automotive  123828                 3
15     Lorelle  Automotive  119959                 3
16   Maryellen  Automotive  115973                 3
17     Ladonna  Automotive  111775                 3
18        Ivie  Automotive  111359                 3
19      Abbott  Automotive  106517                 3
20         Doe  Automotive  106046                 4
21       Vanda  Automotive  103570                 4
22  Clementina  Automotive   95492                 4
23    Jessalyn  Automotive   86929                 4
24    Lauretta  Automotive   75978                 4
25   Archibold  Automotive   69379                 4
26      Katlin  Automotive   60089                 5
27    Sterling  Automotive   56095                 5
28         Way  Automotive   51989                 5
29        Tabb  Automotive   47591                 5
30     Berkley  Automotive   44641                 5
31      Laurie  Automotive   29752                 5
32      Orland      Beauty  162845                 1
33       Urban      Beauty  162169                 1
34      Baxter      Beauty  154018                 1
35       Neddy      Beauty  151926                 1
36      Garald      Beauty  145225                 1
37       Aguie      Beauty  144955                 1
38     Carlyle      Beauty  141315                 1
39      Murray      Beauty  138181                 1

In [39]:
# Create a CTE that returns details of an employee and group the employees into five groups based on the order of their salaries
# Then find the average salary for each group of employees
query = """
WITH salary_ranks AS (
        SELECT first_name, 
               email,
               department, 
               salary,
               NTILE(5) OVER (ORDER BY salary DESC) AS rank_of_salary
        FROM employees
)
SELECT rank_of_salary,
       ROUND(AVG(salary)) AS avg_salary
FROM salary_ranks
GROUP BY rank_of_salary;
"""
pd.read_sql_query(query, conn)

   rank_of_salary  avg_salary
0               1    151648.0
1               2    119197.0
2               3     90136.0
3               4     62086.0
4               5     34791.0

**Aggregate Window Functions**

In [40]:
query = """
-- This returns how many employees are in each department
SELECT department, 
       COUNT(*) AS dept_count
FROM employees
GROUP BY department
ORDER BY department;
"""
pd.read_sql_query(query, conn)

           department  dept_count
0          Automotive          32
1              Beauty          45
2               Books          37
3             Camping          36
4   Children Clothing          47
5            Clothing          49
6           Computers          47
7           Cosmetics          34
8               Decor          39
9       Device Repair          51
10          First Aid          58
11          Furniture          43
12              Games          36
13             Garden          41
14            Grocery          28
15            Jewelry          41
16        Maintenance           8
17             Movies          56
18              Music          29
19           Pharmacy          38
20   Phones & Tablets          35
21           Plumbing           7
22           Security           6
23             Sports          34
24              Tools          39
25               Toys          47
26           Vitamins          37

In [46]:
# Retrieve the first names, department and number of employees working in that department
query = """
SELECT first_name,
       department,
       COUNT(*) OVER(PARTITION BY department) dept_count
FROM employees;
"""
pd.read_sql_query(query, conn)

    first_name  department  dept_count
0        Vanda  Automotive          32
1        Irita  Automotive          32
2      Jilleen  Automotive          32
3       Roslyn  Automotive          32
4       Tammie  Automotive          32
..         ...         ...         ...
995       Lion    Vitamins          37
996       Evin    Vitamins          37
997     Odessa    Vitamins          37
998        Tab    Vitamins          37
999        Fee    Vitamins          37

[1000 rows x 3 columns]

In [61]:
# Total Salary for all employees
query = """
SELECT first_name,
       department, 
       hire_date,
       salary,
       SUM(salary) OVER (PARTITION BY department) AS dept_total_salary,
       COUNT(*) OVER (PARTITION BY department) dept_count
FROM employees
ORDER BY dept_total_salary DESC;
"""
pd.read_sql_query(query, conn)

    first_name department   hire_date  salary  dept_total_salary  dept_count
0        Dayle  First Aid  2003-03-01   82753            5170963          58
1        Aldon  First Aid  2013-06-30  109592            5170963          58
2       Reuben  First Aid  2009-03-14   34572            5170963          58
3       Elnora  First Aid  2003-02-22   34355            5170963          58
4        Elwin  First Aid  2014-07-09  141261            5170963          58
..         ...        ...         ...     ...                ...         ...
995    Kincaid   Security  2010-11-10  162233             539701           6
996      Rorke   Security  2005-01-19   89252             539701           6
997     Gianni   Security  2008-11-20   38963             539701           6
998     Tallie   Security  2006-08-07  146932             539701           6
999    Timothy   Security  2016-08-06   65680             539701           6

[1000 rows x 6 columns]

In [63]:
query = """
-- Total Salary for each department and order by the hire date. Call the new column running_total
SELECT first_name, hire_date, department, salary,
SUM(salary) OVER(PARTITION BY department
				 ORDER BY hire_date) AS running_total
FROM employees
LIMIT 40;
"""
pd.read_sql_query(query, conn)

    first_name   hire_date  department  salary  running_total
0    Maryellen  2003-04-19  Automotive  115973         115973
1    Archibold  2003-04-26  Automotive   69379         185352
2         Tabb  2003-05-02  Automotive   47591         232943
3       Abbott  2003-06-05  Automotive  106517         339460
4      Ladonna  2003-08-10  Automotive  111775         451235
5       Roslyn  2003-08-11  Automotive  157260         608495
6      Lorelle  2004-01-27  Automotive  119959         728454
7        Cybil  2004-04-01  Automotive  123828         852282
8     Sterling  2004-09-02  Automotive   56095         908377
9     Jessalyn  2004-10-03  Automotive   86929         995306
10       Irita  2004-10-15  Automotive  160783        1156089
11         Way  2006-07-15  Automotive   51989        1208078
12      Laurie  2007-05-31  Automotive   29752        1237830
13     Berkley  2007-06-11  Automotive   44641        1282471
14    Lauretta  2007-12-14  Automotive   75978        1358449
15     Merlina  2009-02-16  Automotive  137094        1495543
16        Ivie  2010-04-04  Automotive  111359        1606902
17       Poppy  2010-07-27  Automotive  144511        1751413
18        Mill  2011-01-08  Automotive  162522        1913935
19      Katlin  2011-05-21  Automotive   60089        1974024
20      Tammie  2011-12-08  Automotive  160039        2134063
21      Betsey  2012-02-10  Automotive  152141        2286204
22     Jilleen  2013-04-20  Automotive  137393        2423597
23       Vanda  2014-02-06  Automotive  103570        2527167
24     Chrissy  2014-02-27  Automotive  146522        2673689
25      Noelyn  2014-05-28  Automotive  125305        2798994
26         Doe  2014-10-14  Automotive  106046        2905040
27      Stormy  2015-07-28  Automotive  126983        3032023
28      Charis  2015-08-14  Automotive  130995        3163018
29          Cy  2016-01-18  Automotive  144146        3307164
30  Clementina  2016-09-04  Automotive   95492        3402656
31   Cherianne  2016-12-18  Automotive  150821        3553477
32   Cassandra  2003-01-01      Beauty  106936         106936
33  Willabella  2003-08-18      Beauty   22053         128989
34    Olenolin  2004-09-29      Beauty  137691         266680
35       Lukas  2004-11-03      Beauty   63076         329756
36     Rhianna  2005-04-07      Beauty  120753         450509
37      Kathye  2005-10-09      Beauty   71413         521922
38    Eldredge  2006-04-30      Beauty   60077         581999
39      Garrot  2006-07-10      Beauty   28293         610292

In [64]:
query = """
SELECT first_name,
       department, 
       hire_date,
       salary,
       SUM(salary) OVER (ORDER BY hire_date) AS total_salary
FROM employees
LIMIT 30;
"""
pd.read_sql_query(query, conn)

   first_name         department   hire_date  salary  total_salary
0      Norbie          First Aid  2003-01-01   82215        189151
1   Cassandra             Beauty  2003-01-01  106936        189151
2        Rora  Children Clothing  2003-01-12  153489        342640
3      Feliks          Computers  2003-01-14   55307        397947
4    Cecilius           Vitamins  2003-01-20   98882        496829
5    Eugenius               Toys  2003-01-26  152118        648947
6    Fiorenze   Phones & Tablets  2003-02-17   51266        700213
7      Elnora          First Aid  2003-02-22   34355        734568
8     Chelsey          First Aid  2003-02-24   57309        791877
9    Dorothea            Grocery  2003-02-27   46062        837939
10    Yardley            Jewelry  2003-02-28   26876        864815
11      Dayle          First Aid  2003-03-01   82753        947568
12       Bear              Decor  2003-03-02  143117       1090685
13     Nonnah              Music  2003-03-08  145169       1235854
14      Jamie          Cosmetics  2003-03-13   99770       1335624
15       Arvy             Garden  2003-03-16   76125       1411749
16       Edna  Children Clothing  2003-04-09   91397       1651677
17       Alis              Books  2003-04-09  148531       1651677
18  Maryellen         Automotive  2003-04-19  115973       1767650
19     Dorene              Decor  2003-04-23   97700       1865350
20  Archibold         Automotive  2003-04-26   69379       1934729
21       Tabb         Automotive  2003-05-02   47591       1982320
22  Krystalle              Decor  2003-05-05  135377       2117697
23     Granny             Movies  2003-05-13  125798       2243495
24    Darnall           Clothing  2003-05-23   77589       2321084
25       Eddy              Decor  2003-05-28   99124       2420208
26     Creigh          Furniture  2003-05-31  133537       2553745
27      Byron              Books  2003-06-02   54434       2608179
28     Abbott         Automotive  2003-06-05  106517       2714696
29    Rubetta  Children Clothing  2003-06-07  104955       2819651

In [67]:
query = """
-- Retrieve the different region ids
SELECT DISTINCT region_id
FROM employees
ORDER BY region_id;
"""
pd.read_sql_query(query, conn)

   region_id
0          1
1          2
2          3
3          4
4          5
5          6
6          7

In [81]:
query = """
SELECT first_name,
       department,
       COUNT(*) OVER (PARTITION BY department) AS dept_count,
       region_id,
       COUNT(*) OVER (PARTITION BY region_id) AS region_count
FROM employees
LIMIT 40;
"""
pd.read_sql_query(query, conn)

    first_name  department  dept_count  region_id  region_count
0        Irita  Automotive          32          1           152
1       Roslyn  Automotive          32          1           152
2          Doe  Automotive          32          1           152
3   Clementina  Automotive          32          1           152
4        Cybil  Automotive          32          1           152
5      Chrissy  Automotive          32          1           152
6      Merlina  Automotive          32          1           152
7      Ladonna  Automotive          32          2           141
8       Betsey  Automotive          32          2           141
9        Poppy  Automotive          32          2           141
10   Archibold  Automotive          32          2           141
11     Jilleen  Automotive          32          3           145
12      Charis  Automotive          32          3           145
13       Vanda  Automotive          32          4           137
14      Noelyn  Automotive          32          4           137
15      Laurie  Automotive          32          4           137
16      Tammie  Automotive          32          5           127
17     Berkley  Automotive          32          5           127
18   Maryellen  Automotive          32          5           127
19    Lauretta  Automotive          32          6           146
20      Stormy  Automotive          32          6           146
21   Cherianne  Automotive          32          6           146
22      Katlin  Automotive          32          6           146
23         Way  Automotive          32          6           146
24        Tabb  Automotive          32          6           146
25    Sterling  Automotive          32          7           152
26     Lorelle  Automotive          32          7           152
27    Jessalyn  Automotive          32          7           152
28        Mill  Automotive          32          7           152
29          Cy  Automotive          32          7           152
30      Abbott  Automotive          32          7           152
31        Ivie  Automotive          32          7           152
32     Modesty      Beauty          45          1           152
33     Maurita      Beauty          45          1           152
34    Fredrick      Beauty          45          1           152
35      Garrot      Beauty          45          1           152
36    Eldredge      Beauty          45          1           152
37  Willabella      Beauty          45          2           141
38       Lacee      Beauty          45          2           141
39        Mill      Beauty          45          2           141

In [82]:
query = """
-- Retrieve the first names, department and number of employees working in that department and in region 2
SELECT first_name, department, 
COUNT(*) OVER(PARTITION BY department) AS dept_count
FROM employees
WHERE region_id = 2;
"""
pd.read_sql_query(query, conn)

      first_name  department  dept_count
0        Ladonna  Automotive           4
1         Betsey  Automotive           4
2          Poppy  Automotive           4
3      Archibold  Automotive           4
4     Willabella      Beauty          12
..           ...         ...         ...
136  Archambault    Vitamins           5
137          Ame    Vitamins           5
138       Elvera    Vitamins           5
139        Shell    Vitamins           5
140          Fee    Vitamins           5

[141 rows x 3 columns]

In [83]:
query = """
-- Create a common table expression to retrieve the customer_id, ship_mode, and how many times the customer has purchased from the mall
WITH purchase_count AS (
        SELECT customer_id, 
               ship_mode, 
               COUNT(sales) AS purchase
        FROM sales
        GROUP BY customer_id, ship_mode
        ORDER BY purchase DESC
)

-- Calculate the cumulative sum of customers purchase for the different ship mode
SELECT customer_id, 
       ship_mode, 
       purchase, 
SUM(purchase) OVER(PARTITION BY ship_mode
				   ORDER BY customer_id) AS sum_of_sales
FROM purchase_count;
"""
pd.read_sql_query(query, conn)

     customer_id       ship_mode  purchase  sum_of_sales
0       AA-10315     First Class         1             1
1       AA-10375     First Class         4             5
2       AA-10645     First Class         7            12
3       AB-10015     First Class         5            17
4       AB-10060     First Class         8            25
...          ...             ...       ...           ...
2040    XP-21865  Standard Class        23          5923
2041    YC-21895  Standard Class         5          5928
2042    YS-21880  Standard Class        11          5939
2043    ZC-21910  Standard Class        26          5965
2044    ZD-21925  Standard Class         3          5968

[2045 rows x 4 columns]

**Window Frames**

In [84]:
query = """
SELECT first_name,
       hire_date,
       salary,
       SUM(salary) OVER(ORDER BY hire_date
                        RANGE BETWEEN UNBOUNDED PRECEDING
                        AND CURRENT ROW) AS running_total
FROM employees;
"""
pd.read_sql_query(query, conn)

    first_name   hire_date  salary  running_total
0       Norbie  2003-01-01   82215         189151
1    Cassandra  2003-01-01  106936         189151
2         Rora  2003-01-12  153489         342640
3       Feliks  2003-01-14   55307         397947
4     Cecilius  2003-01-20   98882         496829
..         ...         ...     ...            ...
995     Eloisa  2016-12-02   39200       91125583
996       Edik  2016-12-11   88378       91213961
997      Roxie  2016-12-16   42224       91256185
998  Cherianne  2016-12-18  150821       91407006
999      Barby  2016-12-26  164588       91571594

[1000 rows x 4 columns]

In [85]:
query = """
SELECT first_name,
       hire_date,
       salary,
       SUM(salary) OVER(ORDER BY hire_date
                        ROWS BETWEEN 1 PRECEDING
                        AND CURRENT ROW) AS running_total
FROM employees;
"""
pd.read_sql_query(query, conn)

    first_name   hire_date  salary  running_total
0       Norbie  2003-01-01   82215          82215
1    Cassandra  2003-01-01  106936         189151
2         Rora  2003-01-12  153489         260425
3       Feliks  2003-01-14   55307         208796
4     Cecilius  2003-01-20   98882         154189
..         ...         ...     ...            ...
995     Eloisa  2016-12-02   39200         105584
996       Edik  2016-12-11   88378         127578
997      Roxie  2016-12-16   42224         130602
998  Cherianne  2016-12-18  150821         193045
999      Barby  2016-12-26  164588         315409

[1000 rows x 4 columns]

In [87]:
# Moving average
query = """
SELECT first_name,
       hire_date,
       salary,
       ROUND(AVG(salary) OVER(ORDER BY hire_date
                        ROWS BETWEEN 2 PRECEDING
                        AND CURRENT ROW)) AS running_average
FROM employees;
"""
pd.read_sql_query(query, conn)

    first_name   hire_date  salary  running_average
0       Norbie  2003-01-01   82215          82215.0
1    Cassandra  2003-01-01  106936          94576.0
2         Rora  2003-01-12  153489         114213.0
3       Feliks  2003-01-14   55307         105244.0
4     Cecilius  2003-01-20   98882         102559.0
..         ...         ...     ...              ...
995     Eloisa  2016-12-02   39200          44387.0
996       Edik  2016-12-11   88378          64654.0
997      Roxie  2016-12-16   42224          56601.0
998  Cherianne  2016-12-18  150821          93808.0
999      Barby  2016-12-26  164588         119211.0

[1000 rows x 4 columns]

In [89]:
query = """
SELECT first_name, hire_date, salary,
SUM(salary) OVER(ORDER BY hire_date 
				 ROWS BETWEEN
				 3 PRECEDING AND CURRENT ROW) AS running_total
FROM employees;
"""
pd.read_sql_query(query, conn)

    first_name   hire_date  salary  running_total
0       Norbie  2003-01-01   82215          82215
1    Cassandra  2003-01-01  106936         189151
2         Rora  2003-01-12  153489         342640
3       Feliks  2003-01-14   55307         397947
4     Cecilius  2003-01-20   98882         414614
..         ...         ...     ...            ...
995     Eloisa  2016-12-02   39200         271655
996       Edik  2016-12-11   88378         221540
997      Roxie  2016-12-16   42224         236186
998  Cherianne  2016-12-18  150821         320623
999      Barby  2016-12-26  164588         446011

[1000 rows x 4 columns]

In [ ]:
# Retrieve the last value of the department
query = """
SELECT department, division,
FIRST_VALUE(department) OVER(ORDER BY department ASC) first_department,
LAST_VALUE(department) OVER(ORDER BY department
                            RANGE BETWEEN 
                            UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS last_department
FROM departments;
"""
pd.read_sql_query(query, conn)

           department       division first_department last_department
0          Automotive       Hardware       Automotive        Vitamins
1              Beauty        Fashion       Automotive        Vitamins
2               Books  Entertainment       Automotive        Vitamins
3   Camping & Fishing       Outdoors       Automotive        Vitamins
4   Children Clothing           Kids       Automotive        Vitamins
5            Clothing           Home       Automotive        Vitamins
6           Computers    Electronics       Automotive        Vitamins
7           Cosmetics        Fashion       Automotive        Vitamins
8               Decor           Home       Automotive        Vitamins
9       Device Repair    Electronics       Automotive        Vitamins
10          First Aid         Health       Automotive        Vitamins
11          Furniture           Home       Automotive        Vitamins
12              Games  Entertainment       Automotive        Vitamins
13             Garden       Outdoors       Automotive        Vitamins
14            Grocery           Home       Automotive        Vitamins
15            Jewelry        Fashion       Automotive        Vitamins
16             Movies  Entertainment       Automotive        Vitamins
17              Music  Entertainment       Automotive        Vitamins
18           Pharmacy         Health       Automotive        Vitamins
19   Phones & Tablets    Electronics       Automotive        Vitamins
20             Sports       Outdoors       Automotive        Vitamins
21              Tools       Hardware       Automotive        Vitamins
22               Toys           Kids       Automotive        Vitamins
23           Vitamins         Health       Automotive        Vitamins

In [95]:
query = """
-- Create a common table expression to retrieve the customer_id, ship_mode, and how many times the customer has purchased from the mall
WITH purchase_count AS (
SELECT customer_id, 
       COUNT(sales) AS purchase
FROM sales
GROUP BY customer_id
ORDER BY purchase DESC
)

SELECT customer_id, purchase, 
MAX(purchase) OVER(ORDER BY customer_id ASC) AS max_of_sales,
MAX(purchase) OVER(ORDER BY customer_id ASC
				  ROWS BETWEEN
				  CURRENT ROW AND 1 FOLLOWING) AS next_max_of_sales
FROM purchase_count
LIMIT 40;
"""
pd.read_sql_query(query, conn)

   customer_id  purchase  max_of_sales  next_max_of_sales
0     AA-10315        11            11                 15
1     AA-10375        15            15                 15
2     AA-10480        12            15                 18
3     AA-10645        18            18                 18
4     AB-10015         6            18                 18
5     AB-10060        18            18                 20
6     AB-10105        20            20                 20
7     AB-10150        12            20                 14
8     AB-10165        14            20                 14
9     AB-10255        14            20                 14
10    AB-10600         8            20                  8
11    AC-10420         5            20                  9
12    AC-10450         9            20                 18
13    AC-10615        18            20                 18
14    AC-10660         6            20                 12
15    AD-10180        12            20                 16
16    AF-10870        16            20                 16
17    AF-10885         7            20                 14
18    AG-10270        14            20                 14
19    AG-10300         5            20                  9
20    AG-10330         9            20                  9
21    AG-10390         8            20                 21
22    AG-10495        21            21                 21
23    AG-10525         9            21                 15
24    AG-10675        15            21                 15
25    AG-10765         5            21                 21
26    AG-10900        21            21                 21
27    AH-10030        11            21                 20
28    AH-10075        20            21                 20
29    AH-10120        16            21                 16
30    AH-10195         8            21                 13
31    AH-10210        13            21                 13
32    AH-10465         8            21                  8
33    AH-10585         5            21                 23
34    AH-10690        23            23                 23
35    AI-10855        18            23                 18
36    AJ-10780        15            23                 21
37    AJ-10795        21            23                 21
38    AJ-10945        10            23                 10
39    AJ-10960         5            23                 12

**GROUPING SETS(), ROLLUP(), and CUBE()**

In [97]:
query = """
-- Find the sum of the quantity for different ship modes
SELECT ship_mode, SUM(quantity) AS quantity_per_mode
FROM sales
GROUP BY ship_mode;
"""
pd.read_sql_query(query, conn)

        Ship_Mode  quantity_per_mode
0     First Class               5693
1        Same Day               1960
2    Second Class               7423
3  Standard Class              22797

In [98]:
query = """
-- Find the sum of the quantity for different ship modes
SELECT category, SUM(quantity) AS quantity_per_mode
FROM sales
GROUP BY category;
"""
pd.read_sql_query(query, conn)

          Category  quantity_per_mode
0        Furniture               8028
1  Office Supplies              22906
2       Technology               6939

In [99]:
query = """
-- Find the sum of the quantity for different ship modes
SELECT sub_category, SUM(quantity) AS quantity_per_mode
FROM sales
GROUP BY sub_category;
"""
pd.read_sql_query(query, conn)

   Sub_Category  quantity_per_mode
0   Accessories               2976
1    Appliances               1729
2           Art               3000
3       Binders               5974
4     Bookcases                868
5        Chairs               2356
6       Copiers                234
7     Envelopes                906
8     Fasteners                914
9   Furnishings               3563
10       Labels               1400
11     Machines                440
12        Paper               5178
13       Phones               3289
14      Storage               3158
15     Supplies                647
16       Tables               1241

In [103]:
# Alternative to using GROUPING SETS in SQLite
query = """
SELECT ship_mode, NULL AS category, NULL AS sub_category, SUM(quantity) AS total_quantity
FROM sales
GROUP BY ship_mode

UNION ALL

SELECT NULL, category, NULL, SUM(quantity)
FROM sales
GROUP BY category

UNION ALL

SELECT NULL, NULL, sub_category, SUM(quantity)
FROM sales
GROUP BY sub_category;
"""
pd.read_sql_query(query, conn)

         Ship_Mode         category sub_category  total_quantity
0      First Class              NaN          NaN            5693
1         Same Day              NaN          NaN            1960
2     Second Class              NaN          NaN            7423
3   Standard Class              NaN          NaN           22797
4              NaN        Furniture          NaN            8028
5              NaN  Office Supplies          NaN           22906
6              NaN       Technology          NaN            6939
7              NaN              NaN  Accessories            2976
8              NaN              NaN   Appliances            1729
9              NaN              NaN          Art            3000
10             NaN              NaN      Binders            5974
11             NaN              NaN    Bookcases             868
12             NaN              NaN       Chairs            2356
13             NaN              NaN      Copiers             234
14             NaN              NaN    Envelopes             906
15             NaN              NaN    Fasteners             914
16             NaN              NaN  Furnishings            3563
17             NaN              NaN       Labels            1400
18             NaN              NaN     Machines             440
19             NaN              NaN        Paper            5178
20             NaN              NaN       Phones            3289
21             NaN              NaN      Storage            3158
22             NaN              NaN     Supplies             647
23             NaN              NaN       Tables            1241

In [114]:
# ROLLUP() Alternative in SQLITE
query = """
-- Level 3: grouped by all three columns
SELECT category, sub_category, ship_mode, SUM(quantity) AS total_quantity
FROM sales
GROUP BY category, sub_category, ship_mode

UNION ALL

-- Level 2: grouped by the first two only
SELECT category, sub_category, NULL AS ship_mode, SUM(quantity)
FROM sales
GROUP BY category, sub_category

UNION ALL

-- Level 1: grouped by the first column only
SELECT category, NULL AS sub_category, NULL AS ship_mode, SUM(quantity)
FROM sales
GROUP BY category

UNION ALL

-- Level 0: grand total, no grouping at all
SELECT NULL, NULL, NULL, SUM(quantity)
FROM sales
;
"""
pd.read_sql_query(query, conn)

           Category Sub_Category       Ship_Mode  total_quantity
0         Furniture    Bookcases     First Class             187
1         Furniture    Bookcases        Same Day              19
2         Furniture    Bookcases    Second Class             175
3         Furniture    Bookcases  Standard Class             487
4         Furniture       Chairs     First Class             335
..              ...          ...             ...             ...
84       Technology       Phones             NaN            3289
85        Furniture          NaN             NaN            8028
86  Office Supplies          NaN             NaN           22906
87       Technology          NaN             NaN            6939
88              NaN          NaN             NaN           37873

[89 rows x 4 columns]

In [ ]:
# Alternative to CUBE()-  produces subtotals and grand totals for every permutation of the columns provided.
query = """
-- (category, sub_category, ship_mode)
SELECT category, sub_category, ship_mode, SUM(quantity) AS total_quantity
FROM sales GROUP BY category, sub_category, ship_mode

UNION ALL

-- (category, sub_category)
SELECT category, sub_category, NULL, SUM(quantity)
FROM sales GROUP BY category, sub_category

UNION ALL

-- (category, ship_mode)
SELECT category, NULL, ship_mode, SUM(quantity)
FROM sales GROUP BY category, ship_mode

UNION ALL

-- (sub_category, ship_mode)
SELECT NULL, sub_category, ship_mode, SUM(quantity)
FROM sales GROUP BY sub_category, ship_mode

UNION ALL

-- (category) alone
SELECT category, NULL, NULL, SUM(quantity)
FROM sales GROUP BY category

UNION ALL

-- (sub_category) alone
SELECT NULL, sub_category, NULL, SUM(quantity)
FROM sales GROUP BY sub_category

UNION ALL

-- (ship_mode) alone
SELECT NULL, NULL, ship_mode, SUM(quantity)
FROM sales GROUP BY ship_mode

UNION ALL

-- () grand total
SELECT NULL, NULL, NULL, SUM(quantity)
FROM sales
LIMIT 100;
"""
pd.read_sql_query(query, conn)

      Category Sub_Category       Ship_Mode  total_quantity
0    Furniture    Bookcases     First Class             187
1    Furniture    Bookcases        Same Day              19
2    Furniture    Bookcases    Second Class             175
3    Furniture    Bookcases  Standard Class             487
4    Furniture       Chairs     First Class             335
..         ...          ...             ...             ...
95  Technology          NaN    Second Class            1374
96  Technology          NaN  Standard Class            4122
97         NaN  Accessories     First Class             461
98         NaN  Accessories        Same Day             166
99         NaN  Accessories    Second Class             629

[100 rows x 4 columns]